config/routes.rb
Babel::Application.routes.draw do
  root to: "entries#index"

  resources :entries do
    collection do
      get :search
    end

    resources :codes
  end
end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :entry_id, :url, :language

  belongs_to :entry

  validates :url, :presence => true
  validates :language, :presence => true

  def self.create_with_dirty_language(attributes)
    if dirty = attributes.delete(:language_dirty)
      attributes[:language] = canonicalize_language(dirty)
    end
    create(attributes)
  end

  def self.canonicalize_language(dirty)
    dirty.camelize.gsub(/\s/, "")
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :title

  has_many :codes, :order => "created_at DESC"

  validates :title, :presence => true

  scope :search, lambda { |query|
    where("title like ?", "%#{query}%")
  }

  def modified_on
    if code = codes.first
      code.created_at.to_date
    else
      created_at.to_date
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  def create
    code = Code.create_with_dirty_language(params[:code])
    redirect_to code.entry
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :prepare_entry, :only => :show

  def index
    @entries = Entry.order("created_at DESC").includes(:codes)
  end

  def search
    @entries = Entry.search(params[:query])
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def create
    if @entry = Entry.create(params[:entry])
      redirect_to @entry
    else
      redirect_to entries_path
    end
  end

  private

  def prepare_entry
    @entry = Entry.find_by_id(params[:id]) or
      redirect_to entries_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def unique_class_name
    controller.controller_name + "_" + controller.action_name
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def gist_embed_tag(code)
    javascript_include_tag "#{code.url}.js"
  end

  def label_class_name(str)
    names = [
      "",
      "label-success",
      "label-important",
      "label-warning",
      "label-important",
      "label-info",
      "label-inverse",
    ]
    names[str.to_i(36) % names.size]
  end
end

app/views/entries/_entries.html.slim
ul.entries
  - entries.each do |entry|
    li.entry
      = link_to entry do
        .title
          i.icon-eye-open
          = entry.title

        .date
          i.icon-time
          = entry.modified_on

app/views/entries/_search_form.html.slim
= form_tag search_entries_path, :method => "GET", :class => "form-search" do
  = text_field_tag :query, params[:query]

  = button_tag :class => "btn" do
    i.icon-search

app/views/entries/index.html.slim
section.readme
  h2 What's this?
  p
    | Compare implementation of many algorithms
      in different programming languages.
  p
    | You can post your code by using gist (
    = link_to "?", "https://gist.github.com"
    | ).

section.entries_section
  h2 Recent Entries

  = render "entries", :entries => @entries

section.search_section
  h2 Search

  = render "search_form"

app/views/entries/new.html.slim
h2 Create a new entry

= form_for @entry do |f|
  .title
    = f.text_field :title, :placeholder => "title"

  .submit
    = button_tag :class => "btn" do
      i.icon-file
      | Create

app/views/entries/search.html.slim
section.entries_section
  h2 Entries

  = render "entries", :entries => @entries

section.search_section
  h2 Search

  = render "search_form"

app/views/entries/show.html.slim
section
  h3.title
    i.icon-chevron-right
    = @entry.title

section
  ul.codes
    - @entry.codes.each do |code|
      li.code
        .tag
          span.label*{:class => label_class_name(code.language)}
            = code.language

        .embed
          = gist_embed_tag(code)

section
  = form_tag [@entry, :codes] do
    = hidden_field_tag "code[entry_id]", @entry.id

    .language
      = text_field_tag "code[language_dirty]", "", :placeholder => "Perl or Ruby or etc..."

    .url
      = text_field_tag "code[url]", "", :placeholder => "https://gist.github.com/12345678"

    .submit
      = button_tag :class => "btn" do
        i.icon-plus-sign
        | Add a new code

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Babel

    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Press+Start+2P"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body*{:id => unique_class_name}
    header#header
      h1
        = link_to root_path do
          | Babel

      .add
        = link_to new_entry_path do
          i.icon-plus

    #main
      = yield

    footer#footer
      = link_to "http://twitter.com/r7kamura" do
        p.yunotti
          | ✘╹◡╹✘
        p.name
          | @r7kamura